global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: guardian-backend
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - guardian-backend.guardianai.svc.cluster.local:8001
    labels:
      service: guardian-backend
      app: guardianai
